// <auto-generated />
using System;
using DotaNerf.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotaNerf.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250619200011_PasswordHashing")]
    partial class PasswordHashing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotaNerf.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DireTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RadiantTeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("WinningTeam")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DireTeamId")
                        .IsUnique();

                    b.HasIndex("RadiantTeamId")
                        .IsUnique();

                    b.ToTable("Games");
                });

            modelBuilder.Entity("DotaNerf.Entities.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Heroes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Abaddon"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Alchemist"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ancient Apparition"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Anti-Mage"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Arc Warden"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Axe"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Bane"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Batrider"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Beastmaster"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Bloodseeker"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Bounty Hunter"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Brewmaster"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Bristleback"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Broodmother"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Centaur Warrunner"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Chaos Knight"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Chen"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Clinkz"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Clockwerk"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Crystal Maiden"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Dark Seer"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Dark Willow"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Dawnbreaker"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Dazzle"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Death Prophet"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Disruptor"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Doom"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Dragon Knight"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Drow Ranger"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Earth Spirit"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Earthshaker"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Elder Titan"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Ember Spirit"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Enchantress"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Enigma"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Faceless Void"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Grimstroke"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Gyrocopter"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Hoodwink"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Huskar"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Invoker"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Io"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Jakiro"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Juggernaut"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Keeper of the Light"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Kunkka"
                        },
                        new
                        {
                            Id = 121,
                            Name = "Kez"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Legion Commander"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Leshrac"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Lich"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Lifestealer"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Lina"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Lion"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Lone Druid"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Luna"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Lycan"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Magnus"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Marci"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Mars"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Medusa"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Meepo"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Mirana"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Monkey King"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Morphling"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Muerta"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Naga Siren"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Nature's Prophet"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Necrophos"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Night Stalker"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Nyx Assassin"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Ogre Magi"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Omniknight"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Oracle"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Outworld Destroyer"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Pangolier"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Phantom Assassin"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Phantom Lancer"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Phoenix"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Primal Beast"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Puck"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Pudge"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Pugna"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Queen of Pain"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Razor"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Riki"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Rubick"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Ringmaster"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Sand King"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Shadow Demon"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Shadow Fiend"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Shadow Shaman"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Silencer"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Skywrath Mage"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Slardar"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Slark"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Snapfire"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Sniper"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Spectre"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Spirit Breaker"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Storm Spirit"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Sven"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Techies"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Templar Assassin"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Terrorblade"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Tidehunter"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Timbersaw"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Tinker"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Tiny"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Treant Protector"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Troll Warlord"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Tusk"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Underlord"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Undying"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Ursa"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Vengeful Spirit"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Venomancer"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Viper"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Void Spirit"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Warlock"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Wraith King"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Zeus"
                        });
                });

            modelBuilder.Entity("DotaNerf.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PlayerDetailsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0de33ebf-6f2d-4f37-a41f-c92a8387a16f"),
                            Name = "Veni",
                            PlayerDetailsId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000002")
                        },
                        new
                        {
                            Id = new Guid("158f0cd7-315a-4d60-8a4a-3537766b2958"),
                            Name = "Retar Dio ( kolega )",
                            PlayerDetailsId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000003")
                        },
                        new
                        {
                            Id = new Guid("2637179a-65b0-4af7-b7b2-0dc0b044a9c6"),
                            Name = "Steli",
                            PlayerDetailsId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000004")
                        },
                        new
                        {
                            Id = new Guid("2f08b795-c2ee-460f-9102-489dcb034a59"),
                            Name = "Kriskata",
                            PlayerDetailsId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000005")
                        },
                        new
                        {
                            Id = new Guid("2f25fdca-7016-4c2b-904e-154813b60210"),
                            Name = "DJ misho",
                            PlayerDetailsId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000006")
                        },
                        new
                        {
                            Id = new Guid("2f3ab1f0-f334-4239-8793-87d92239d5bb"),
                            Name = "Stoqn (kolega )",
                            PlayerDetailsId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000007")
                        },
                        new
                        {
                            Id = new Guid("32830ea1-39ad-469c-96bd-3040f2d49f6a"),
                            Name = "Kuncho",
                            PlayerDetailsId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000008")
                        },
                        new
                        {
                            Id = new Guid("35b0e246-4545-4079-b258-8ba67ac756fa"),
                            Name = "Sofianeca",
                            PlayerDetailsId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000009")
                        },
                        new
                        {
                            Id = new Guid("013986ba-03a2-4e5f-a54e-1e1a677c5593"),
                            Name = "Marto",
                            PlayerDetailsId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000001")
                        },
                        new
                        {
                            Id = new Guid("3d6a9560-592d-49e5-bfe6-29d2fe589d42"),
                            Name = "Rumen",
                            PlayerDetailsId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000010")
                        },
                        new
                        {
                            Id = new Guid("3e85b928-0684-4300-9a23-c4d3c64ab59f"),
                            Name = "Bobur Kurva",
                            PlayerDetailsId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000011")
                        },
                        new
                        {
                            Id = new Guid("40270ce1-9235-4720-9097-b26fcd7ebdc3"),
                            Name = "Vaneto",
                            PlayerDetailsId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000012")
                        },
                        new
                        {
                            Id = new Guid("45193089-0738-40c2-951b-ec481ca21786"),
                            Name = "Mario",
                            PlayerDetailsId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000013")
                        },
                        new
                        {
                            Id = new Guid("4f1f9cac-418b-4356-94c6-144eac70c0a9"),
                            Name = "Panic",
                            PlayerDetailsId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000014")
                        },
                        new
                        {
                            Id = new Guid("5514f903-232a-4866-9e0b-4740b56de8fc"),
                            Name = "The Joker",
                            PlayerDetailsId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000015")
                        },
                        new
                        {
                            Id = new Guid("6119f1a3-884c-4f22-9fa4-401e55917378"),
                            Name = "Danithedog",
                            PlayerDetailsId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000016")
                        },
                        new
                        {
                            Id = new Guid("617747ee-a832-47be-aa30-c99310456113"),
                            Name = "Nevermore",
                            PlayerDetailsId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000017")
                        },
                        new
                        {
                            Id = new Guid("632691d7-db1b-4fb5-9e83-893250e14474"),
                            Name = "Mode : topuria",
                            PlayerDetailsId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000018")
                        },
                        new
                        {
                            Id = new Guid("71e4bb90-31dd-4cf7-9628-9eb8462e8a03"),
                            Name = "Zloto kuche",
                            PlayerDetailsId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000019")
                        },
                        new
                        {
                            Id = new Guid("75c32438-809f-4f31-9ae3-d79ad2b56c29"),
                            Name = "Baba Yaga",
                            PlayerDetailsId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000020")
                        },
                        new
                        {
                            Id = new Guid("8441c8de-e7e7-4faa-9869-99e95fa0791b"),
                            Name = "Smurf",
                            PlayerDetailsId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000021")
                        },
                        new
                        {
                            Id = new Guid("90eae6b2-6395-49a8-9bfa-df51eac66c90"),
                            Name = "Peacelock",
                            PlayerDetailsId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000022")
                        },
                        new
                        {
                            Id = new Guid("a7af794d-dbdc-4a05-a4f4-ebbb1ef0a0fb"),
                            Name = "Vee",
                            PlayerDetailsId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000023")
                        },
                        new
                        {
                            Id = new Guid("a807403e-9e93-4a3b-9a4b-6eb9a6406687"),
                            Name = "RMZ",
                            PlayerDetailsId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000024")
                        },
                        new
                        {
                            Id = new Guid("c3219456-5c5d-4d18-9980-032627844744"),
                            Name = "teperkules",
                            PlayerDetailsId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000025")
                        },
                        new
                        {
                            Id = new Guid("cce185ad-c8d0-48ba-ad96-2ed4508b7dad"),
                            Name = "Vetirinari",
                            PlayerDetailsId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000026")
                        },
                        new
                        {
                            Id = new Guid("d226779e-6c47-46a2-96cf-89f6c7502018"),
                            Name = "Borat BG",
                            PlayerDetailsId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000027")
                        },
                        new
                        {
                            Id = new Guid("d5d3d965-f59c-46ce-8bb4-929cc261491a"),
                            Name = "Pro 1",
                            PlayerDetailsId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000028")
                        },
                        new
                        {
                            Id = new Guid("d68b00ec-3ee2-4069-aa06-c74dce1946ce"),
                            Name = "Fisheye",
                            PlayerDetailsId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000029")
                        },
                        new
                        {
                            Id = new Guid("e7cc43a2-1eb1-4df4-837a-e264d386a235"),
                            Name = "Batko bie sladko prime",
                            PlayerDetailsId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000030")
                        },
                        new
                        {
                            Id = new Guid("eb3228bc-8b90-41b5-8a5a-e9faaf5e9048"),
                            Name = "pitbgr",
                            PlayerDetailsId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000031")
                        },
                        new
                        {
                            Id = new Guid("f5071dec-ea3e-4106-8d52-bb3f59fdb3aa"),
                            Name = "Svetorontotokyo",
                            PlayerDetailsId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000032")
                        },
                        new
                        {
                            Id = new Guid("f6f06957-a84d-4071-87d0-4b08e29888c5"),
                            Name = "Rei",
                            PlayerDetailsId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000033")
                        });
                });

            modelBuilder.Entity("DotaNerf.Entities.PlayerDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GamesLost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("GamesWon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("PlayerGroup")
                        .HasColumnType("int");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalGames")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<double>("Winrate")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("PlayerDetails");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000001"),
                            GamesLost = 0,
                            GamesWon = 0,
                            PlayerGroup = 0,
                            PlayerId = new Guid("013986ba-03a2-4e5f-a54e-1e1a677c5593"),
                            TotalGames = 0,
                            Winrate = 0.0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000002"),
                            GamesLost = 0,
                            GamesWon = 0,
                            PlayerGroup = 0,
                            PlayerId = new Guid("0de33ebf-6f2d-4f37-a41f-c92a8387a16f"),
                            TotalGames = 0,
                            Winrate = 0.0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000003"),
                            GamesLost = 0,
                            GamesWon = 0,
                            PlayerGroup = 1,
                            PlayerId = new Guid("158f0cd7-315a-4d60-8a4a-3537766b2958"),
                            TotalGames = 0,
                            Winrate = 0.0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000004"),
                            GamesLost = 0,
                            GamesWon = 0,
                            PlayerGroup = 1,
                            PlayerId = new Guid("2637179a-65b0-4af7-b7b2-0dc0b044a9c6"),
                            TotalGames = 0,
                            Winrate = 0.0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000005"),
                            GamesLost = 0,
                            GamesWon = 0,
                            PlayerGroup = 0,
                            PlayerId = new Guid("2f08b795-c2ee-460f-9102-489dcb034a59"),
                            TotalGames = 0,
                            Winrate = 0.0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000006"),
                            GamesLost = 0,
                            GamesWon = 0,
                            PlayerGroup = 0,
                            PlayerId = new Guid("2f25fdca-7016-4c2b-904e-154813b60210"),
                            TotalGames = 0,
                            Winrate = 0.0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000007"),
                            GamesLost = 0,
                            GamesWon = 0,
                            PlayerGroup = 1,
                            PlayerId = new Guid("2f3ab1f0-f334-4239-8793-87d92239d5bb"),
                            TotalGames = 0,
                            Winrate = 0.0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000008"),
                            GamesLost = 0,
                            GamesWon = 0,
                            PlayerGroup = 0,
                            PlayerId = new Guid("32830ea1-39ad-469c-96bd-3040f2d49f6a"),
                            TotalGames = 0,
                            Winrate = 0.0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000009"),
                            GamesLost = 0,
                            GamesWon = 0,
                            PlayerGroup = 0,
                            PlayerId = new Guid("35b0e246-4545-4079-b258-8ba67ac756fa"),
                            TotalGames = 0,
                            Winrate = 0.0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000010"),
                            GamesLost = 0,
                            GamesWon = 0,
                            PlayerGroup = 0,
                            PlayerId = new Guid("3d6a9560-592d-49e5-bfe6-29d2fe589d42"),
                            TotalGames = 0,
                            Winrate = 0.0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000011"),
                            GamesLost = 0,
                            GamesWon = 0,
                            PlayerGroup = 1,
                            PlayerId = new Guid("3e85b928-0684-4300-9a23-c4d3c64ab59f"),
                            TotalGames = 0,
                            Winrate = 0.0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000012"),
                            GamesLost = 0,
                            GamesWon = 0,
                            PlayerGroup = 0,
                            PlayerId = new Guid("40270ce1-9235-4720-9097-b26fcd7ebdc3"),
                            TotalGames = 0,
                            Winrate = 0.0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000013"),
                            GamesLost = 0,
                            GamesWon = 0,
                            PlayerGroup = 0,
                            PlayerId = new Guid("45193089-0738-40c2-951b-ec481ca21786"),
                            TotalGames = 0,
                            Winrate = 0.0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000014"),
                            GamesLost = 0,
                            GamesWon = 0,
                            PlayerGroup = 1,
                            PlayerId = new Guid("4f1f9cac-418b-4356-94c6-144eac70c0a9"),
                            TotalGames = 0,
                            Winrate = 0.0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000015"),
                            GamesLost = 0,
                            GamesWon = 0,
                            PlayerGroup = 1,
                            PlayerId = new Guid("5514f903-232a-4866-9e0b-4740b56de8fc"),
                            TotalGames = 0,
                            Winrate = 0.0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000016"),
                            GamesLost = 0,
                            GamesWon = 0,
                            PlayerGroup = 1,
                            PlayerId = new Guid("6119f1a3-884c-4f22-9fa4-401e55917378"),
                            TotalGames = 0,
                            Winrate = 0.0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000017"),
                            GamesLost = 0,
                            GamesWon = 0,
                            PlayerGroup = 2,
                            PlayerId = new Guid("617747ee-a832-47be-aa30-c99310456113"),
                            TotalGames = 0,
                            Winrate = 0.0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000018"),
                            GamesLost = 0,
                            GamesWon = 0,
                            PlayerGroup = 2,
                            PlayerId = new Guid("632691d7-db1b-4fb5-9e83-893250e14474"),
                            TotalGames = 0,
                            Winrate = 0.0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000019"),
                            GamesLost = 0,
                            GamesWon = 0,
                            PlayerGroup = 2,
                            PlayerId = new Guid("71e4bb90-31dd-4cf7-9628-9eb8462e8a03"),
                            TotalGames = 0,
                            Winrate = 0.0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000020"),
                            GamesLost = 0,
                            GamesWon = 0,
                            PlayerGroup = 1,
                            PlayerId = new Guid("75c32438-809f-4f31-9ae3-d79ad2b56c29"),
                            TotalGames = 0,
                            Winrate = 0.0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000021"),
                            GamesLost = 0,
                            GamesWon = 0,
                            PlayerGroup = 2,
                            PlayerId = new Guid("8441c8de-e7e7-4faa-9869-99e95fa0791b"),
                            TotalGames = 0,
                            Winrate = 0.0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000022"),
                            GamesLost = 0,
                            GamesWon = 0,
                            PlayerGroup = 2,
                            PlayerId = new Guid("90eae6b2-6395-49a8-9bfa-df51eac66c90"),
                            TotalGames = 0,
                            Winrate = 0.0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000023"),
                            GamesLost = 0,
                            GamesWon = 0,
                            PlayerGroup = 2,
                            PlayerId = new Guid("a7af794d-dbdc-4a05-a4f4-ebbb1ef0a0fb"),
                            TotalGames = 0,
                            Winrate = 0.0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000024"),
                            GamesLost = 0,
                            GamesWon = 0,
                            PlayerGroup = 2,
                            PlayerId = new Guid("a807403e-9e93-4a3b-9a4b-6eb9a6406687"),
                            TotalGames = 0,
                            Winrate = 0.0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000025"),
                            GamesLost = 0,
                            GamesWon = 0,
                            PlayerGroup = 2,
                            PlayerId = new Guid("c3219456-5c5d-4d18-9980-032627844744"),
                            TotalGames = 0,
                            Winrate = 0.0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000026"),
                            GamesLost = 0,
                            GamesWon = 0,
                            PlayerGroup = 1,
                            PlayerId = new Guid("cce185ad-c8d0-48ba-ad96-2ed4508b7dad"),
                            TotalGames = 0,
                            Winrate = 0.0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000027"),
                            GamesLost = 0,
                            GamesWon = 0,
                            PlayerGroup = 1,
                            PlayerId = new Guid("d226779e-6c47-46a2-96cf-89f6c7502018"),
                            TotalGames = 0,
                            Winrate = 0.0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000028"),
                            GamesLost = 0,
                            GamesWon = 0,
                            PlayerGroup = 2,
                            PlayerId = new Guid("d5d3d965-f59c-46ce-8bb4-929cc261491a"),
                            TotalGames = 0,
                            Winrate = 0.0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000029"),
                            GamesLost = 0,
                            GamesWon = 0,
                            PlayerGroup = 2,
                            PlayerId = new Guid("d68b00ec-3ee2-4069-aa06-c74dce1946ce"),
                            TotalGames = 0,
                            Winrate = 0.0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000030"),
                            GamesLost = 0,
                            GamesWon = 0,
                            PlayerGroup = 2,
                            PlayerId = new Guid("e7cc43a2-1eb1-4df4-837a-e264d386a235"),
                            TotalGames = 0,
                            Winrate = 0.0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000031"),
                            GamesLost = 0,
                            GamesWon = 0,
                            PlayerGroup = 2,
                            PlayerId = new Guid("eb3228bc-8b90-41b5-8a5a-e9faaf5e9048"),
                            TotalGames = 0,
                            Winrate = 0.0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000032"),
                            GamesLost = 0,
                            GamesWon = 0,
                            PlayerGroup = 2,
                            PlayerId = new Guid("f5071dec-ea3e-4106-8d52-bb3f59fdb3aa"),
                            TotalGames = 0,
                            Winrate = 0.0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-000000000033"),
                            GamesLost = 0,
                            GamesWon = 0,
                            PlayerGroup = 2,
                            PlayerId = new Guid("f6f06957-a84d-4071-87d0-4b08e29888c5"),
                            TotalGames = 0,
                            Winrate = 0.0
                        });
                });

            modelBuilder.Entity("DotaNerf.Entities.PlayerGame", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GameId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerGames");
                });

            modelBuilder.Entity("DotaNerf.Entities.PlayerStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Assists")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("Deaths")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HeroPlayedId")
                        .HasColumnType("int");

                    b.Property<int?>("Kills")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("HeroPlayedId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("PlayerStats");
                });

            modelBuilder.Entity("DotaNerf.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("DotaNerf.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .IsUnicode(false)
                        .HasColumnType("varchar(320)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("550e8400-e29b-41d4-a716-446655440000"),
                            Email = "admin@dotanerf.com",
                            Password = "7Tf0uhxZnxOl1kLN7wzNNg==.CvoJhIIZ2cWEyiWy15Qw/CLHYZQZJE7KvKDW/Wrq7cM=",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("PlayerTeam", b =>
                {
                    b.Property<Guid>("PlayersId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeamsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PlayersId", "TeamsId");

                    b.HasIndex("TeamsId");

                    b.ToTable("PlayerTeams", (string)null);
                });

            modelBuilder.Entity("DotaNerf.Entities.Game", b =>
                {
                    b.HasOne("DotaNerf.Entities.Team", "DireTeam")
                        .WithOne()
                        .HasForeignKey("DotaNerf.Entities.Game", "DireTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DotaNerf.Entities.Team", "RadiantTeam")
                        .WithOne()
                        .HasForeignKey("DotaNerf.Entities.Game", "RadiantTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DireTeam");

                    b.Navigation("RadiantTeam");
                });

            modelBuilder.Entity("DotaNerf.Entities.PlayerDetails", b =>
                {
                    b.HasOne("DotaNerf.Entities.Player", "Player")
                        .WithOne("PlayerDetails")
                        .HasForeignKey("DotaNerf.Entities.PlayerDetails", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DotaNerf.Entities.PlayerGame", b =>
                {
                    b.HasOne("DotaNerf.Entities.Game", "Game")
                        .WithMany("PlayerGames")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotaNerf.Entities.Player", "Player")
                        .WithMany("PlayerGames")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("DotaNerf.Entities.PlayerStats", b =>
                {
                    b.HasOne("DotaNerf.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotaNerf.Entities.Hero", "HeroPlayed")
                        .WithMany()
                        .HasForeignKey("HeroPlayedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotaNerf.Entities.Player", "Player")
                        .WithMany("PlayerStats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotaNerf.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("HeroPlayed");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("DotaNerf.Entities.Team", b =>
                {
                    b.HasOne("DotaNerf.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("PlayerTeam", b =>
                {
                    b.HasOne("DotaNerf.Entities.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotaNerf.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DotaNerf.Entities.Game", b =>
                {
                    b.Navigation("PlayerGames");
                });

            modelBuilder.Entity("DotaNerf.Entities.Player", b =>
                {
                    b.Navigation("PlayerDetails")
                        .IsRequired();

                    b.Navigation("PlayerGames");

                    b.Navigation("PlayerStats");
                });
#pragma warning restore 612, 618
        }
    }
}
